### ISSUE TITLE
Failed to play song due to an internal error.

### ISSUE THREAD

**Issue by ghost** [ItzDerock/simplevoicechat-music#5]
[13:49:11] [SVCMusicExecutor/INFO]: Starting new audio frame sending task.
[13:49:12] [lava-daemon-pool-playback-1-thread-1/ERROR]: Error in playback of HQnC1UHBvWA
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[simple-voice-chat-music-0.2.0.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[simple-voice-chat-music-0.2.0.jar:?]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[simple-voice-chat-music-0.2.0.jar:?]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[simple-voice-chat-music-0.2.0.jar:?]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[simple-voice-chat-music-0.2.0.jar:?]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[simple-voice-chat-music-0.2.0.jar:?]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[simple-voice-chat-music-0.2.0.jar:?]
        ... 4 more
[13:49:12] [lava-daemon-pool-playback-1-thread-1/ERROR]: Failed to play Porter Robinson & Madeon - Shelter (Official Audio) due to error: Something broke when playing the track.

**Comment by ItzDerock** [comment]
Is this consistently happening when playing this track? and do other tracks work properly?

**Comment by ItzDerock** [comment]
Able to reproduce, likely related to #4.

**Comment by kylianpl** [comment]
Updated `dev.arbjerg:lavaplayer` to `2.2.2` and `dev.lavalink.youtube:v2` to `1.8.3` and it works

**Comment by Aldresxk** [comment]
> Updated `dev.arbjerg:lavaplayer` to `2.2.2` and `dev.lavalink.youtube:v2` to `1.8.3` and it works

como lo hago
